### ISSUE TITLE
Duplicate help entries

### ISSUE THREAD

**Issue by devops-rob** [target-cli/target#5]
The help output has duplicate entries

```
target vault
Manage Vault context profiles.

Usage:
  target vault [command]

Available Commands:
  create      create command creates a context profile
  delete      delete removes a context profile
  delete      delete removes a context profile
  list        
  list        
  rename      rename a conext profile
  select      select a context profile
  update      Update an existing context

Flags:
  -h, --help   help for vault

Use "target vault [command] --help" for more information about a command.
```

In this case, its list and delete that are duplicated.

This happens for Vault, Nomad and Consul sub commands

**Comment by devops-rob** [comment]
I found the issue. It is duplicate init funcs with the same sub command definitions. I'll fix it in the next merge

**Comment by devops-rob** [comment]
Fixed in [this merge](https://github.com/target-cli/target/commit/72158c55aef020be4f775d698aee7f0d603b14bb)

**Comment by yermulnik** [comment]
Can confirm issue still exists for the new installation:
```shell
> target version
Current Version: 1.0.0

> target <tab><tab>
boundary
boundary    (Manage Boundary context profiles)
completion  (Generate the autocompletion script for the specified shell)
config
config      (Configure target CLI for shell sessions)
consul
consul      (Manage consul context profiles)
help        (Help about any command)
nomad
nomad       (Manage Nomad context profiles)
terraform
terraform   (Manage Terraform context profiles)
vault
vault       (Manage Vault context profiles)
version
version     (Show current installed version of target-cli)

**Comment by yermulnik** [comment]
```shell
> fgrep -w VERSION /etc/os-release
VERSION="22.04.3 LTS (Jammy Jellyfish)"
```
and
```shell
> fgrep -w VERSION /etc/os-release
VERSION="19.3 (Tricia)"
```

ps: the latter is a bit outdated though is for the sake of example
